call makefnt.bat 08 Y
call makefnt_bold.bat 09b Y
call makefnt.bat 10 Y
call makefnt_bold.bat 10b Y
call makefnt_bold.bat 11e Y
call makefnt_bold.bat 11s Y
call makefnt.bat 12 Y
call makefnt.bat 12ss Y
call makefnt_bold.bat 13e Y
call makefnt.bat 14 Y
call makefnt.bat 16 Y
call makefnt.bat 16b Y
call makefnt_bold.bat 16e Y
call makefnt_bold.bat 16s Y
call makefnt.bat 18 Y
call makefnt_bold.bat 18b Y
call makefnt.bat 20 Y
call makefnt.bat 20_16 Y
call makefnt_bold.bat 20b Y
call makefnt.bat 24 Y
call makefnt_bold.bat 24b Y
call makefnt_bold.bat 30 Y
call makefnt_bold.bat feicomment Y
call makefnt.bat miniscenario Y
call makefnt.bat plugin Y
call makefnt_bold.bat tutorial Y
pac_pack.exe UpdateCHS
